In [14]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

In [9]:
housing_data = fetch_california_housing(as_frame = True)

housing_df = housing_data.data

In [12]:
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [15]:
# https://www.kaggle.com/datasets/jackksoncsie/spam-email-dataset
# https://www.kaggle.com/datasets/rabieelkharoua/cancer-prediction-dataset?resource=download


#Age: Integer values representing the patient's age, ranging from 20 to 80.
#Gender: Binary values representing gender, where 0 indicates Male and 1 indicates Female.
#BMI: Continuous values representing Body Mass Index, ranging from 15 to 40.
#Smoking: Binary values indicating smoking status, where 0 means No and 1 means Yes.
#GeneticRisk: Categorical values representing genetic risk levels for cancer, with 0 indicating Low, 1 indicating Medium, and 2 indicating High.
#PhysicalActivity: Continuous values representing the number of hours per week spent on physical activities, ranging from 0 to 10.
#AlcoholIntake: Continuous values representing the number of alcohol units consumed per week, ranging from 0 to 5.
#CancerHistory: Binary values indicating whether the patient has a personal history of cancer, where 0 means No and 1 means Yes.
#Diagnosis: Binary values indicating the cancer diagnosis status, where 0 indicates No Cancer and 1 indicates Cancer.

cancer_data = pd.read_csv('data/cancer-data.csv')

In [16]:
cancer_data

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory,Diagnosis
0,58,1,16.085313,0,1,8.146251,4.148219,1,1
1,71,0,30.828784,0,1,9.361630,3.519683,0,0
2,48,1,38.785084,0,2,5.135179,4.728368,0,1
3,34,0,30.040296,0,0,9.502792,2.044636,0,0
4,62,1,35.479721,0,0,5.356890,3.309849,0,1
...,...,...,...,...,...,...,...,...,...
1495,62,1,25.090025,0,0,9.892167,1.284158,0,1
1496,31,0,33.447125,0,1,1.668297,2.280636,1,1
1497,63,1,32.613861,1,1,0.466848,0.150101,0,1
1498,55,0,25.568216,0,0,7.795317,1.986138,1,1
1499,67,1,23.663104,0,0,2.525860,2.856600,1,0

In [ ]:
X = df

In [ ]:
# LDA and QDA in scikit

# https://scikit-learn.org/stable/modules/lda_qda.html